---
- name: Check user1 exists
  hosts: all
  gather_facts: false
  tasks:
    - name: Get list of users
      ansible.builtin.getent:
        database: passwd

    - name: Check user exists
      ansible.builtin.assert:
        that: "'user1' in ansible_facts.getent_passwd"

- name: Check user1 has privileges
  hosts: ssh-instance-01
  gather_facts: false
  tasks:
    - name: user1 use sudo privilege
      remote_user: user1
      become: yes
      ansible.builtin.file:
        path: /etc/user1
        owner: user1
        state: touch
        mode: '0750'
      failed_when: False

    - name: Get file user1 info
      ansible.builtin.stat:
        path: /etc/user1
      register: stat_result1

    - name: Check that the file user1 exists
      ansible.builtin.assert:
        that: stat_result1.stat.exists

- name: Check user1 does not have privileges
  hosts: ssh-instance-02
  gather_facts: false
  tasks:
    - name: user1 use sudo privilege
      remote_user: user1
      become: yes
      ansible.builtin.file:
        path: /etc/user1
        owner: user1
        state: touch
        mode: '0750'
      failed_when: False

    - name: Get file user1 info
      ansible.builtin.stat:
        path: /etc/user1
      register: stat_result1

    - name: Check that the file user1 does not exist
      ansible.builtin.assert:
        that: not stat_result1.stat.exists
