---
# tasks file for role_name

- name: Create std group
  ansible.builtin.group:
    name: "std_group"
    state: present

- name: Create root group
  ansible.builtin.group:
    name: "root_group"
    state: present

- name: Allow root_group run sudo without password
  ansible.builtin.copy:
    dest: "/etc/sudoers"
    mode: "440"
    content: |
      %root_group      ALL=(ALL)       NOPASSWD: ALL

- name: Add root user
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "root_group"
    shell: /bin/bash
    state: "{{ item.state }}"
  with_items: "{{ users }}"
  when: item.root|ansible.builtin.bool

- name: Add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "std_group"
    shell: /bin/bash
    state: "{{ item.state }}"
  with_items: "{{ users }}"
  when: not item.root|ansible.builtin.bool

- name: Remove ssh keys for users
  ansible.builtin.file:
    path: "/home/{{item.name}}/.ssh/authorized_keys"
    state: absent
  with_items: "{{ users }}"
  when: item.state == "present"

- name: Set ssh keys for users
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ lookup('file', item.1) }}"
    state: present
  with_subelements:
    - "{{ users }}"
    - ssh
  when: item.0.state == "present"