---
# tasks file for role_name

- name: Create root group
  ansible.builtin.group:
    name: "root_group"
    state: present

- name: Add root user
  ansible.builtin.user:
    name: "{{ item.user.name }}"
    group: "root_group"
    shell: /bin/bash
    state: present
  with_items: "{{ root_users }}"

- name: Allow root group run sudo without password
  ansible.builtin.copy:
    dest: "/etc/sudoers"
    mode: "440"
    content: |
      %root_group      ALL=(ALL)       NOPASSWD: ALL

- name: Create standard group
  ansible.builtin.group:
    name: "standard_group"
    state: present

- name: Add standard users
  ansible.builtin.user:
    name: "{{ item.user.name }}"
    group: "standard_group"
    shell: /bin/bash
    state: present
  with_items: "{{ standard_users }}"

- name: Set ssh keys for root users
  ansible.posix.authorized_key:
    user: "{{ item.user.name }}"
    key: "{{ lookup('file', item.user.ssh) }}"
    exclusive: yes
    state: present
  with_items: "{{ root_users }}"

- name: Set ssh keys for standard users
  ansible.posix.authorized_key:
    user: "{{ item.user.name }}"
    key: "{{ lookup('file', item.user.ssh) }}"
    exclusive: yes
    state: present
  with_items: "{{ standard_users }}"
