---
- name: Create root group
  ansible.builtin.group:
    name: "root_group"
    state: present

- name: Allow root_group run sudo without password
  ansible.builtin.lineinfile:
    create: true
    state: present
    regex: '^%root_group'
    dest: "/etc/sudoers"
    mode: "440"
    line: '%root_group      ALL=(ALL)       NOPASSWD: ALL'

# TODO: Unite next 2 tasks
- name: Add root user
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: ["root_group"]
    shell: /bin/bash
    state: "{{ item.state }}"
  loop: "{{ users }}"
  when: item.sudo | ansible.builtin.bool

- name: Add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: ''
    shell: /bin/bash
    state: "{{ item.state }}"
  loop: "{{ users }}"
  when: not item.sudo | ansible.builtin.bool

- name: Set ssh keys for users
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.key }}"
    state: "{{ item.1.state | default('present')}}"
  loop: "{{ users|subelements('ssh') }}"
  when: item.0.state == "present"
