---
- name: Add users
  hosts: all
  vars:
    users:
      - name: user1
        state: present
        sudo: true
        ssh:
          - key: "{{ lookup('file', 'ssh_sample/ssh_user1.pub') }}"
      - name: user2
        state: present
        sudo: false
        ssh:
          - key: "{{ lookup('file', 'ssh_sample/ssh_user2.pub') }}"
  roles:
    - { role: cloud_labs.ssh_user }
