dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ssh-instance-01
    hostname: ssh-instance-01
    image: davidlor/python-ssh
    groups:
      - etcd
    pre_build_image: true
  - name: ssh-instance-02
    hostname: ssh-instance-02
    image: davidlor/python-ssh
    groups:
      - etcd
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      ssh-instance-01:
        ansible_user: root
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
scenario:
  name: add_user
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy